---
presubmits:
  # PR job triggering definitions.
  # Keys: Full repo name: "org/repo".
  # Values: List of jobs to run when events occur in the repo.
  #   name:          Job name.
  #   trigger:       Regexp commenters can say to trigger the job.
  #   always_run:    Whether to run for every PR. Default is false. If this is
  #                  set then your trigger needs to match "@k8s-bot test this".
  #   context:       GitHub status context.
  #   rerun_command: How should users trigger just this job, as a string, not a
  #                  regex. For example, if the trigger regex is "(e2e )?test",
  #                  then a rerun command might be "e2e test".
  #   skip_report:   If true, then do not set status or comment on GitHub.
  #   spec:          If this exists then run a kubernetes pod with this spec.
  #                  Otherwise, run a Jenkins job.

  nlandolfi/test-infra:
  - name: basic-build
    context: jobs/basic-build.sh
    always_run: true
    rerun_command: "@prowbot bazel build this"
    trigger: "@prowbot (bazel )?build this"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/isito-prow/bazel:0.23
        imagePullPolicy: Always
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
  - name: basic-test
    context: jobs/basic-test.sh
    always_run: true
    rerun_command: "@prowbot bazel test this"
    trigger: "@prowbot (bazel )?test this"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/isito-prow/bazel:0.23
        imagePullPolicy: Always
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account

  nlandolfi/pilot:
  - name: pilot-presubmit
    context: jobs/pilot-presubmit.sh
    always_run: true
    rerun_command: "@prowbot bazel test this"
    trigger: "@prowbot (bazel )?test this"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/isito-prow/bazel:0.23
        imagePullPolicy: Always
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
    run_after_success:
      - name: pilot-e2e-smoketest
        context: jobs/pilot-e2e-smoketest.sh
        always_run: true
        rerun_command: "@prowbot e2e test this"
        trigger: "@prowbot e2e test this"
        branches:
        - master
        spec:
          containers:
          - image: gcr.io/isito-prow/bazel:0.23
            imagePullPolicy: Always
            args:
            - "--pull=$(PULL_REFS)"
            - "--clean"
            # Bazel needs privileged mode in order to sandbox builds.
            securityContext:
              privileged: true
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/service-account/service-account.json
            volumeMounts:
            - name: service
              mountPath: /etc/service-account
              readOnly: true
          volumes:
          - name: service
            secret:
              secretName: service-account

  nlandolfi/proxy:
  - name: proxy-presubmit
    context: jobs/proxy-presubmit.sh
    always_run: true
    rerun_command: "@prowbot bazel test this"
    trigger: "@prowbot (bazel )?test this"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/isito-prow/bazel:0.23
        imagePullPolicy: Always
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
