#!/usr/bin/env bash
# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# Clone the repository, and enter
echo "> Cloning: ${REPO_OWNER}/${REPO_NAME}"
git clone https://github.com/${REPO_OWNER}/${REPO_NAME}.git
cd ${REPO_NAME}

# Fetch the pull request branch, and enter
# TODO(nclandolfi): ref resolution
echo "> Branching: pull/${PULL_NUMBER}"
git fetch origin pull/${PULL_NUMBER}/head:prow
git checkout prow

if [! -2 ./.prow/${JOB_NAME}.sh ]; then
    echo "./prow/${JOB_NAME}.sh does not exist"
    exit 1
fi

echo "> Running: ./prow/${JOB_NAME}.sh"

./prow/${JOB_NAME}.sh

if [ $? != 0 ]; then
    echo "> Run failed"
fi

# exit with status code of previous command
exit $?
