#!/bin/bash

# set -o errexit
set -o nounset
# set -o pipefail

env

# Clone the repository, and enter
echo "> Cloning: ${REPO_OWNER}/${REPO_NAME}"
git clone https://github.com/${REPO_OWNER}/${REPO_NAME}.git
cd ${REPO_NAME}

# Fetch the pull request branch, and enter
# TODO(nclandolfi): ref resolution
echo "> Branching: pull/${PULL_NUMBER}"
git fetch origin pull/${PULL_NUMBER}/head:prow
git checkout prow

gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
gcloud config get-value account

mkdir /artifacts

echo "> Running: ./jobs/${JOB_NAME}.sh"

// /artifacts exists, gcloud works, and we are in root dir of repo
./jobs/${JOB_NAME}.sh > ./stdout.txt 2> ./stderr.txt

RUN_RESULT=$?

if [ $RUN_RESULT != 0 ]; then
    echo "> Run FAILURE"
fi

if [ $RUN_RESULT == 0 ]; then
    echo "> Run SUCCESS"
fi

echo "> Uploading..."

# mark this as a job dir for gub
touch /.job.json
gsutil -q -h Content-Type:application/json cp /.job.json gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/

# upload stdout and stderr
gsutil -q -h Content-Type:text/plain cp ./std*.txt gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/

# upload /artifacts/**/*
if [ "$(ls -A /artifacts)" ]; then
    echo "...and artifacts:"
    ls /artifacts
    gsutil -q -h Content-Type:text/plain cp -r /artifacts/**/* gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/artifacts/
else
    echo "...NO artifacts"
fi

echo "> Uploaded to: gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/"

# exit with status code of job
exit $RUN_RESULT
