#!/usr/bin/env bash
# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

env

# Clone the repository, and enter
echo "> Cloning: ${REPO_OWNER}/${REPO_NAME}"
git clone https://github.com/${REPO_OWNER}/${REPO_NAME}.git
cd ${REPO_NAME}

# Fetch the pull request branch, and enter
# TODO(nclandolfi): ref resolution
echo "> Branching: pull/${PULL_NUMBER}"
git fetch origin pull/${PULL_NUMBER}/head:prow
git checkout prow

gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
gcloud config get-value account

mkdir /artifacts

echo "> Running: ./jobs/${JOB_NAME}.sh"

./jobs/${JOB_NAME}.sh > ./stdout.txt 2> ./stderr.txt

RUN_RESULT=$?

if [ $RUN_RESULT != 0 ]; then
    echo "> Run FAILURE"
fi

if [ $RUN_RESULT == 0 ]; then
    echo "> Run SUCCESS"
fi

echo "> Uploading..."

gsutil -q -h Content-Type:text/plain cp ./std*.txt gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/

if [ "$(ls -A /artifacts)" ]; then
    echo "...and artifacts"
    gsutil -q -h Content-Type:text/plain cp /artifacts/* gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/artifacts/
else
    echo "...NO artifacts"
fi

echo "> Uploaded to: gs://precise-firmament-3016/jobs/${REPO_OWNER}/${REPO_NAME}/${JOB_NAME}/${BUILD_NUMBER}/"

# exit with status code of job
exit $RUN_RESULT
